
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 13 08:27:02 COT 2015
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABPARENT = 3;
  public static final int MAS = 2;
  public static final int PALABRA = 5;
  public static final int error = 1;
  public static final int CEPARENT = 4;
  public static final int EOF = 0;
}

